// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using P2P.Infrastructure.Persistence;

#nullable disable

namespace P2P.Infrastructure.Persistence.PlatformMigrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260829180301_AddPlatformAdminUser")]
    partial class AddPlatformAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("P2P.Domain.Platform.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeploymentTarget")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrgCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrgCode")
                        .IsUnique();

                    b.HasIndex("SchemaName")
                        .IsUnique();

                    b.ToTable("organisations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-4d5f-8f9b-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DeploymentTarget = 0,
                            DisplayName = "Acme Corporation",
                            OrgCode = "acme",
                            SchemaName = "org_acme",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-4d5f-8f9b-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DeploymentTarget = 0,
                            DisplayName = "Globex Corporation",
                            OrgCode = "globex",
                            SchemaName = "org_globex",
                            Status = 1
                        });
                });

            modelBuilder.Entity("P2P.Domain.Platform.PlatformAdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("platform_admin_user", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
